services:
  db:
    image: postgres:15
    container_name: fsdb-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fsdb
      POSTGRES_USER: fsdb_user
      POSTGRES_PASSWORD: supersecret
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080

  # bot:
  #   build: .
  #   container_name: fsdb-bot
  #   restart: unless-stopped
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgres://fsdb_user:supersecret@db:5432/fsdb

  bot:
    image: ghcr.io/firstslovenia/fsdb
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://fsdb_user:supersecret@db:5432/fsdb

volumes:
  postgres_data:
